### ISSUE TITLE
[spike] Analyze and define the epic scope and tasks

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#217]
As part of this task, please investigate the process of a firmware upgrade. Figure out:
- [x] Which devices should be supported initially
- [x] Analyze the need to create a simple POC code for firmware upgrade vs immediately implement this process in enodebd
- [x] Analyze the scope based on the requirements and define the tasks

FW Upgrade functionality is partially covered in: https://docs.google.com/document/d/1KFSQOL6YGg546r75JZ9JuS3h512j2X6Q9vzeu-M_49o

**Comment by xbend** [comment]
Initial review of enodebd code shows that we can implement this inside enodebd already.
POC code seems unnecessary as we would then have to recreate a http TR069 session server which is extra work - not needed in fact since enodebd already has that implemented.

enodebd modification will be initially done for Sercomm (Freedomfi one) eNB.
